# Generated by Django 4.2.6 on 2023-10-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='subject',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
